services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/usr/share/nginx/html
  node: 
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - "3000:3000"
  react-app:
    image: node:latest
    volumes:
      - ./code/03-counter-app-cra:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    ports:
      - "3001:3000"
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
  react-vite-app:
    image: node:latest
    volumes:
      - ./code/03-counter-app-vite:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3002:5173"
    stdin_open: true
    tty: true